import createClient from 'openapi-fetch';
import debug from 'debug';
import type { paths } from './api-schema'; // generated by openapi-typescript

const log = debug('api');

// Get base URL from environment or use empty string for proxy
const getBaseUrl = () => {
  // In development with proxy, use relative path
  if (process.env.NODE_ENV === 'development') {
    return '';
  }
  // In production or when explicitly set, use the full URL
  return process.env.UMI_APP_SERVER_URL || 'http://127.0.0.1:8000';
};

const client = createClient<paths>({
  baseUrl: getBaseUrl(),
});

client.use({
  onResponse({ response }) {
    // log(response);
    // if (response.status >= 200) {
    //   notification.error({
    //     message: 'Error',
    //     description: response.statusText,
    //   });
    // }
  },
});

export { client };
